Models/ErrorViewModel.cs
namespace AvaliacaoLp3Bim3.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ViewModels/EstabelecimentoViewModel.cs
namespace AvaliacaoLp3Bim3.ViewModels;

public class EstabelecimentoViewModel
{
    public int? Id { get; set; }
    public string? Nome { get; set; }
    public string? Piso { get; set; }
    public string? Descricao { get; set; }
    public string? LojaKiosque { get; set; }
    public string? Email { get; set; }

    public EstabelecimentoViewModel(int id, string nome, string piso, string descricao, string lojaKiosque, string email)
    {
        Id = id;
        Nome = nome;
        Piso = piso;
        Descricao = descricao;
        LojaKiosque = lojaKiosque;
        Email = email;
    }

    public EstabelecimentoViewModel()
    {
        
    }

}

Controllers/EstabelecimentoController.cs
using Microsoft.AspNetCore.Mvc;
using AvaliacaoLp3Bim3.ViewModels;

namespace AvaliacaoLp3Bim3.Controllers;

public class EstabelecimentoController : Controller
{
    private static List<EstabelecimentoViewModel> estabelecimentos = new List<EstabelecimentoViewModel>(); 

    public IActionResult Index()
    {
        return View(estabelecimentos);
    }

    public IActionResult Gerenciamento()
    {
        return View(estabelecimentos);
    }

    public IActionResult Show(int id)
    {
        // foreach com intuito de deixar dinâmico, visto que os índices da lista também são dinâmicos
        foreach(var estabelecimento in estabelecimentos)
        {
            if(estabelecimento.Id == id)
            {
                return View(estabelecimento);
            }
        }

        // valor default de retorno
        return View(estabelecimentos[0]);
    }

    public IActionResult CadastrarEstabelecimento()
    {
        return View();
    }

    public IActionResult Adicionar(EstabelecimentoViewModel viewModel)
    {
        foreach(var estabelecimento in estabelecimentos)
        {
            //não permite o cadastro de estabelecimentos com mesmo nome ou id, fazendo com que só haja o redirecionamento, sem a criação de uma nova loja
            if(estabelecimento.Nome == viewModel.Nome || estabelecimento.Id == viewModel.Id)
            {
                return RedirectToAction("Gerenciamento");
            }
        }

        estabelecimentos.Add(viewModel);
        return RedirectToAction("Gerenciamento");
    }

    public IActionResult Excluir(int id)
    {
        foreach(var estabelecimento in estabelecimentos.ToList())
        {
            if(estabelecimento.Id == id)
            {
                estabelecimentos.Remove(estabelecimento);
            }
        }
        return RedirectToAction("Gerenciamento");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AvaliacaoLp3Bim3.Models;

namespace AvaliacaoLp3Bim3.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Estabelecimento/CadastrarEstabelecimento.cshtml
@{
    ViewData["Title"] = "Cadastrar Estabelecimento";
}

<h1>Cadastrar Estabelecimento</h1>
<p>Utilize o formulário para Cadastrar um estabelecimento</p>

<form action="/Estabelecimento/Adicionar" method="POST">
    <label for="id">ID</label>
    <input type="number" id="id" name="Id">

    <label for="nome">Nome</label>
    <input type="text" id="nome" name="Nome">

    <label for="piso">Piso</label>
    <select name="Piso" id="piso">
        <option value="Piso 1">Piso 1</option>
        <option value="Piso 2">Piso 2</option>
        <option value="Piso 3">Piso 3</option>
    </select>

    <label for="descricao">Descrição</label>
    <textarea name="Descricao" id="descricao"></textarea>

    <label for="lojaKiosque">Loja / Kiosque</label>
    <select name="LojaKiosque" id="lojaKiosque">
        <option value="Loja">Loja</option>
        <option value="Kiosque">Kiosque</option>
    </select>

    <label for="email">Email</label>
    <input type="email" id="email" name="Email">

    <input class="submit" type="submit" value="Adicionar">
</form>

Views/Estabelecimento/Gerenciamento.cshtml
@model List<AvaliacaoLp3Bim3.ViewModels.EstabelecimentoViewModel>

@{
    ViewData["Title"] = "Gerenciamento de Estabelecimentos";
}

<h1>Gerenciamento de Estabelecimentos</h1>
@if(Model.Count == 0)
{
    <p>Não há nenhum estabelecimento cadastrado.</p>
    <a  href="/Estabelecimento/CadastrarEstabelecimento">Cadastre um estabelecimento</a>
}
else
{
    <p>A quantidade de estabelecimentos cadastrados é: @Model.Count</p>
    <hr>

    @foreach(var loja in Model)
    {
        <a  href="/Estabelecimento/Show/@loja.Id">
            <h3>@loja.Nome</h3>
        </a>
        <p>@loja.Descricao</p>
        <a  href="/Estabelecimento/Excluir/@loja.Id">Excluir</a>
        <hr>
    }

    <a href="/Estabelecimento/CadastrarEstabelecimento">Cadastre um estabelecimento</a>
}

Views/Estabelecimento/Index.cshtml
@model List<AvaliacaoLp3Bim3.ViewModels.EstabelecimentoViewModel>

@{
    ViewData["Title"] = "Lista de Estabelecimento";
}

<h1>Estabelecimentos</h1>
@if(Model.Count == 0)
{
    <p>Não há nenhum estabelecimento cadastrado.</p>
}
else
{
    @foreach(var loja in Model)
    {
        <h3>@loja.Nome</h3>
        <p>@loja.Descricao</p>
        <hr>
    }
}

Views/Estabelecimento/Show.cshtml
@model AvaliacaoLp3Bim3.ViewModels.EstabelecimentoViewModel

@{
    ViewData["Title"] = "Detalhe do Estabelecimento";
}

<h1>@Model.Nome</h1>
<hr>
<a href="/Estabelecimento/Excluir/@Model.Id">Excluir</a>
<hr>
<p>Id: @Model.Id</p>
<p>Nome: @Model.Nome</p>
<p>Descrição: @Model.Descricao</p>
<p>Piso: @Model.Piso</p>
<p>Tipo de Estabelecimento: @Model.LojaKiosque</p>
<p>Email: @Model.Email</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvaliacaoLp3Bim3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AvaliacaoLp3Bim3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AvaliacaoLp3Bim3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estabelecimento" asp-action="Index">Estabelecimentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estabelecimento" asp-action="Gerenciamento">Gerenciamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estabelecimento" asp-action="CadastrarEstabelecimento">Cadastrar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AvaliacaoLp3Bim3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>